# Generated by Django 4.0.3 on 2022-03-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist_files',
            old_name='files',
            new_name='file',
        ),
    ]
