# Generated by Django 4.0.3 on 2022-03-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_files_todolist_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist_images',
            name='todo',
        ),
        migrations.AddField(
            model_name='todolist',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='이미지'),
        ),
        migrations.DeleteModel(
            name='TodoList_files',
        ),
        migrations.DeleteModel(
            name='TodoList_images',
        ),
    ]
