# Generated by Django 4.0.3 on 2022-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todolist_images_todo_todolist_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
    ]
