# Generated by Django 4.0.3 on 2022-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_file_alter_todolist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
