# Generated by Django 4.0.3 on 2022-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolist_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='파일'),
        ),
    ]
