# Generated by Django 4.0.3 on 2022-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todolist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Task'),
        ),
    ]
