# Generated by Django 4.0.3 on 2022-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('content', models.TextField(max_length=200, verbose_name='content')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='file')),
            ],
        ),
    ]
