# Generated by Django 4.0.3 on 2022-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Info',
        ),
    ]
