# Generated by Django 4.0.3 on 2022-03-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='질문제목')),
                ('content', models.TextField(verbose_name='질문내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.question', verbose_name='답변제목')),
            ],
        ),
    ]
