# Generated by Django 4.0.3 on 2022-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일시'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일시'),
        ),
    ]
