# Generated by Django 4.0.3 on 2022-04-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_answer_modify_date_question_modify_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='board/images', verbose_name='photo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.question', verbose_name='imagepost')),
            ],
        ),
    ]
